const dummyData = {
    message: 'File processed successfully',
    data: [
      {
        studentName: 'Aarav Sharma',
        rollNumber: '2023001',
        marks: 78,
        totalMarks: 100,
        subject: 'Mathematics',
        question1Marks: 18,
        question2Marks: 20,
        question3Marks: 15,
        question4Marks: 25,
        status: 'Valid',
      },
      {
        studentName: 'Isha Verma',
        rollNumber: '2023002',
        marks: 65,
        totalMarks: 100,
        subject: 'Science',
        question1Marks: 10,
        question2Marks: 20,
        question3Marks: 15,
        question4Marks: 20,
        status: 'Valid',
      },
      {
        studentName: 'Rajesh Kumar',
        rollNumber: '2023003',
        marks: 50,
        totalMarks: 100,
        subject: 'History',
        question1Marks: 12,
        question2Marks: 8,
        question3Marks: 15,
        question4Marks: 15,
        status: 'Needs Attention',
      },
      {
        studentName: 'Nisha Mehta',
        rollNumber: '2023004',
        marks: 92,
        totalMarks: 100,
        subject: 'English',
        question1Marks: 20,
        question2Marks: 20,
        question3Marks: 22,
        question4Marks: 30,
        status: 'Valid',
      },
      {
        studentName: 'Aryan Singh',
        rollNumber: '2023005',
        marks: 40,
        totalMarks: 100,
        subject: 'Geography',
        question1Marks: 10,
        question2Marks: 10,
        question3Marks: 8,
        question4Marks: 12,
        status: 'Needs Attention',
      },
    ],
  };
  