export const FETCH_TABLE_DATA = 'FETCH_TABLE_DATA';
export const UPDATE_TABLE_ROW = 'UPDATE_TABLE_ROW';
export const DELETE_TABLE_ROW = 'DELETE_TABLE_ROW';
export const ADD_TABLE_ROW = 'ADD_TABLE_ROW';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';